name: Publish ibm-segment

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      # increment the patch version and commit the change
      - name: Bump version and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch -m "chore: bump version to %s"
          git push

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
